### ISSUE TITLE
Error when starting bot

### ISSUE THREAD

**Issue by NotWes** [NotWes/Growconomy-Bot#3]
...\events\message.js:30
    console.log("Error While Running Command " + ${cmd.help.name} + ":" + e);
                                                 ^

SyntaxError: missing ) after argument list
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by NotWes** [comment]
New Error Top one fixed.

Event Loaded: message
Event Loaded: ready
Command Loaded: ping
(node:8168) UnhandledPromiseRejectionWarning: ReferenceError: prefix is not defined
    at Object.module.exports.run (/root/Growconomy-Bot/events/ready.js:2:68)
    at Client.client.on.args (/root/Growconomy-Bot/index.js:21:53)
    at emitNone (events.js:111:20)
    at Client.emit (events.js:208:7)
    at WebSocketConnection.triggerReady (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
    at GuildCreateHandler.handle (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
(node:8168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
