### ISSUE TITLE
Commands dont work

### ISSUE THREAD

**Issue by NotWes** [NotWes/Growconomy-Bot#7]
(node:8405) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'push' of undefined
    at Object.module.exports.run (/root/Growconomy-Bot/events/message.js:8:15)
    at Client.client.on.args (/root/Growconomy-Bot/index.js:21:53)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/root/Growconomy-Bot/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
(node:8405) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8405) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NotWes** [comment]
Top fixed new:

(node:8433) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at Object.module.exports.run (/root/Growconomy-Bot/events/message.js:28:59)
    at Client.client.on.args (/root/Growconomy-Bot/index.js:21:53)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/root/Growconomy-Bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/root/Growconomy-Bot/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
(node:8433) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8433) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NotWes** [comment]
Top fixed New:

(node:8491) UnhandledPromiseRejectionWarning: ReferenceError: Discord is not defined
    at Object.module.exports.run (/root/Growconomy-Bot/commands/ping.js:6:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:8491) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8491) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NotWes** [comment]
Closed.
